backend:
  name: git-gateway
  branch: master # o "master" se usi ancora master

media_folder: "assets/uploads" # cartella per le immagini nel repo
public_folder: "/assets/uploads" # percorso pubblico per le immagini

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
